input_text_desired_length: 110
input_text_max_length: 170
selected_theme: freddyaboulton/dracula_revamped
server_name: ''
server_port: 0
server_share: false
silence_between_sentences: 250
silence_between_speakers: 500
selected_language: english